# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
     odd_even_checker:
         class: NewBundle\Services\OddEvenChecker
     meta_info_printer:
         class: NewBundle\Services\MetaInfoPrinter
         arguments: ['@odd_even_checker']
     request_listener:
         class: NewBundle\Listeners\RequestListener
         tags:
             - { name: kernel.event_listener, event: kernel.request }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
